// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeadkssyfynsryusefbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlYWRrc3N5Znluc3J5dXNlZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTI2OTIsImV4cCI6MjA2NzgyODY5Mn0.XO0d1iF1amiyHPvniy94l1Z8iMSSgOiqh2ab7YeZ1Qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});